spring:
  application:
    name: springboot-redis-cache

  redis:
    host: 192.168.211.3
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    password:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
    type-aliases-package: com.ygl.springboot.redis.cache.entity
    mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.ygl.springboot.redis.cache.mapper:
      debug

